import {
  Home24Regular,
  Settings24Regular,
  Play24Regular,
  CloudArrowDown24Regular,
  DocumentBulletList24Regular,
  Folder24Regular,
  TaskListSquareLtr24Regular,
  HeartPulse24Regular,
  Lightbulb24Regular,
  ChannelShare24Regular,
  ChartMultiple24Regular,
  FlashFlow24Regular,
  Wand24Regular,
  Eye24Regular,
  Database24Regular,
  LocalLanguage24Regular,
  DocumentText24Regular,
  Speaker224Regular,
  DataUsage24Regular,
  ShieldCheckmark24Regular,
  DocumentSearch24Regular,
  Stethoscope24Regular,
  DataUsage24Regular as Dashboard24Regular,
  Add24Regular,
  Grid24Regular,
  ImageMultiple24Regular,
  Video24Regular,
  PlugConnected24Regular,
} from '@fluentui/react-icons';

export interface NavItem {
  key: string;
  name: string;
  icon: React.ComponentType;
  path: string;
  advancedOnly?: boolean;
}

export const navItems: NavItem[] = [
  { key: 'home', name: 'Welcome', icon: Home24Regular, path: '/' },
  { key: 'dashboard', name: 'Dashboard', icon: Dashboard24Regular, path: '/dashboard' },
  { key: 'ideation', name: 'Ideation', icon: Lightbulb24Regular, path: '/ideation' },
  { key: 'trending', name: 'Trending Topics', icon: ChartMultiple24Regular, path: '/trending' },
  {
    key: 'usage-analytics',
    name: 'Usage Analytics',
    icon: DataUsage24Regular,
    path: '/usage-analytics',
  },
  { key: 'create', name: 'Create', icon: Add24Regular, path: '/create' },
  { key: 'templates', name: 'Templates', icon: Grid24Regular, path: '/templates' },
  { key: 'projects', name: 'Projects', icon: Folder24Regular, path: '/projects' },
  { key: 'assets', name: 'Asset Library', icon: ImageMultiple24Regular, path: '/assets' },
  { key: 'editor', name: 'Video Editor', icon: Video24Regular, path: '/editor' },
  { key: 'opencut', name: 'OpenCut', icon: Video24Regular, path: '/opencut' },
  {
    key: 'pacing',
    name: 'Pacing Analyzer',
    icon: FlashFlow24Regular,
    path: '/pacing',
    advancedOnly: true,
  },
  { key: 'render', name: 'Render', icon: Play24Regular, path: '/render' },
  { key: 'platform', name: 'Platform Optimizer', icon: ChannelShare24Regular, path: '/platform' },
  { key: 'quality', name: 'Quality Dashboard', icon: ChartMultiple24Regular, path: '/quality' },

  { key: 'jobs', name: 'Recent Jobs', icon: TaskListSquareLtr24Regular, path: '/jobs' },
  {
    key: 'downloads',
    name: 'Program Dependencies',
    icon: CloudArrowDown24Regular,
    path: '/downloads',
  },
  { key: 'health', name: 'Provider Health', icon: HeartPulse24Regular, path: '/health' },
  {
    key: 'providers',
    name: 'Providers Dashboard',
    icon: PlugConnected24Regular,
    path: '/providers',
  },
  {
    key: 'ai-editing',
    name: 'AI Editing',
    icon: Wand24Regular,
    path: '/ai-editing',
    advancedOnly: true,
  },
  {
    key: 'aesthetics',
    name: 'Visual Aesthetics',
    icon: Eye24Regular,
    path: '/aesthetics',
    advancedOnly: true,
  },
  { key: 'models', name: 'AI Models', icon: Database24Regular, path: '/models' },
  {
    key: 'localization',
    name: 'Localization',
    icon: LocalLanguage24Regular,
    path: '/localization',
  },
  {
    key: 'prompt-management',
    name: 'Prompt Management',
    icon: DocumentText24Regular,
    path: '/prompt-management',
    advancedOnly: true,
  },
  {
    key: 'rag',
    name: 'RAG Documents',
    icon: DocumentSearch24Regular,
    path: '/rag',
  },
  {
    key: 'voice-enhancement',
    name: 'Voice Enhancement',
    icon: Speaker224Regular,
    path: '/voice-enhancement',
  },
  {
    key: 'verification',
    name: 'Content Verification',
    icon: ShieldCheckmark24Regular,
    path: '/verification',
  },
  { key: 'diagnostics', name: 'Diagnostics', icon: Stethoscope24Regular, path: '/diagnostics' },
  { key: 'logs', name: 'Logs', icon: DocumentBulletList24Regular, path: '/logs' },
  {
    key: 'admin',
    name: 'Admin Dashboard',
    icon: ShieldCheckmark24Regular,
    path: '/admin',
    advancedOnly: true,
  },
  { key: 'settings', name: 'Settings', icon: Settings24Regular, path: '/settings' },
];
