using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Aura.Core.Data;

/// <summary>
/// Entity for storing semantic asset metadata generated by AI providers.
/// Enables LLM-intelligent asset selection during video generation.
/// </summary>
public class SemanticAssetMetadataEntity : IAuditableEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Guid AssetId { get; set; }

    [MaxLength(2000)]
    public string? Description { get; set; }

    [MaxLength(50)]
    public string? DominantColor { get; set; }

    [MaxLength(100)]
    public string? Mood { get; set; }

    [MaxLength(200)]
    public string? Subject { get; set; }

    /// <summary>
    /// JSON-serialized embedding vector for semantic similarity search
    /// </summary>
    public string? EmbeddingJson { get; set; }

    [Required]
    public DateTime TaggedAt { get; set; }

    [MaxLength(100)]
    public string? TaggingProvider { get; set; }

    public float? ConfidenceScore { get; set; }

    // Navigation properties
    public List<SemanticAssetTagEntity> Tags { get; set; } = new();

    // IAuditableEntity
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public string? ModifiedBy { get; set; }
}

/// <summary>
/// Entity for storing individual semantic tags with confidence and category.
/// </summary>
public class SemanticAssetTagEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Guid MetadataId { get; set; }

    [Required]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    [Required]
    public float Confidence { get; set; }

    [Required]
    [MaxLength(50)]
    public string Category { get; set; } = "Subject";

    public DateTime CreatedAt { get; set; }

    // Navigation properties
    public SemanticAssetMetadataEntity? Metadata { get; set; }
}
