using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Aura.Api.Migrations
{
    /// <summary>
    /// Adds the SemanticAssetTags table for LLM-intelligent asset selection.
    /// This table stores semantic metadata generated by AI providers like Ollama.
    /// </summary>
    public partial class AddSemanticAssetTags : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create SemanticAssetMetadata table for storing AI-generated semantic metadata
            migrationBuilder.CreateTable(
                name: "SemanticAssetMetadata",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    AssetId = table.Column<Guid>(type: "TEXT", nullable: false),
                    Description = table.Column<string>(type: "TEXT", maxLength: 2000, nullable: true),
                    DominantColor = table.Column<string>(type: "TEXT", maxLength: 50, nullable: true),
                    Mood = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    Subject = table.Column<string>(type: "TEXT", maxLength: 200, nullable: true),
                    EmbeddingJson = table.Column<string>(type: "TEXT", nullable: true),
                    TaggedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    TaggingProvider = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    ConfidenceScore = table.Column<float>(type: "REAL", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SemanticAssetMetadata", x => x.Id);
                });

            // Create SemanticAssetTags table for storing AI-generated tags with confidence and category
            migrationBuilder.CreateTable(
                name: "SemanticAssetTags",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    MetadataId = table.Column<Guid>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    Confidence = table.Column<float>(type: "REAL", nullable: false),
                    Category = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SemanticAssetTags", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SemanticAssetTags_SemanticAssetMetadata_MetadataId",
                        column: x => x.MetadataId,
                        principalTable: "SemanticAssetMetadata",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // Create indexes for efficient querying
            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetMetadata_AssetId",
                table: "SemanticAssetMetadata",
                column: "AssetId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetMetadata_TaggedAt",
                table: "SemanticAssetMetadata",
                column: "TaggedAt");

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetMetadata_Mood",
                table: "SemanticAssetMetadata",
                column: "Mood");

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetMetadata_Subject",
                table: "SemanticAssetMetadata",
                column: "Subject");

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetTags_MetadataId",
                table: "SemanticAssetTags",
                column: "MetadataId");

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetTags_Name",
                table: "SemanticAssetTags",
                column: "Name");

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetTags_Category",
                table: "SemanticAssetTags",
                column: "Category");

            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetTags_Confidence",
                table: "SemanticAssetTags",
                column: "Confidence");

            // Create combined index for tag lookups
            migrationBuilder.CreateIndex(
                name: "IX_SemanticAssetTags_Name_Category",
                table: "SemanticAssetTags",
                columns: new[] { "Name", "Category" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "SemanticAssetTags");
            migrationBuilder.DropTable(name: "SemanticAssetMetadata");
        }
    }
}
