// <auto-generated />
using System;
using Aura.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aura.Api.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    [Migration("20251109170431_AddSystemConfiguration")]
    partial class AddSystemConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Aura.Core.Data.ActionLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResourceIds")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanBatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InverseActionType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InversePayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndoneByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Aura.Core.Data.AssetStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsTemporary");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "AssetType");

                    b.ToTable("AssetStates");
                });

            modelBuilder.Entity("Aura.Core.Data.ConfigurationEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsSensitive");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Category", "IsActive");

                    b.HasIndex("Category", "UpdatedAt");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Aura.Core.Data.ContentBlobEntity", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReferencedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContentHash");

                    b.HasIndex("ContentType");

                    b.HasIndex("LastReferencedAt");

                    b.HasIndex("ReferenceCount");

                    b.ToTable("ContentBlobs");
                });

            modelBuilder.Entity("Aura.Core.Data.CustomTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LLMPipelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptStructureJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoStructureJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualPreferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDefault");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.ToTable("CustomTemplates");
                });

            modelBuilder.Entity("Aura.Core.Data.ExportHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Codec")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codec");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("InputFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("input_file");

                    b.Property<string>("OutputFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_file");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("preset_name");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL")
                        .HasColumnName("progress");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("export_history");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentWizardStep")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceSpecJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("ProjectStates");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMarkedImportant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("StorageSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimelineHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceSpecJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsMarkedImportant");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionType");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.HasIndex("ProjectId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("Aura.Core.Data.RenderCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckpointTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedScenes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScenes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointTime");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "StageName");

                    b.ToTable("RenderCheckpoints");
                });

            modelBuilder.Entity("Aura.Core.Data.SceneStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "SceneIndex");

                    b.ToTable("SceneStates");
                });

            modelBuilder.Entity("Aura.Core.Data.SystemConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FFmpegPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ffmpeg_path");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_setup_complete");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_directory");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("system_configuration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 17, 4, 31, 236, DateTimeKind.Utc).AddTicks(5323),
                            IsSetupComplete = false,
                            OutputDirectory = "/home/runner/AuraVideoStudio/Output",
                            UpdatedAt = new DateTime(2025, 11, 9, 17, 4, 31, 236, DateTimeKind.Utc).AddTicks(5324)
                        });
                });

            modelBuilder.Entity("Aura.Core.Data.TemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsCommunityTemplate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_community_template");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PreviewImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_image");

                    b.Property<string>("PreviewVideo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_video");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating_count");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_category");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsCommunityTemplate");

                    b.HasIndex("IsSystemTemplate");

                    b.HasIndex("Category", "SubCategory");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("Aura.Core.Data.UserSetupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("LastStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_step");

                    b.Property<string>("SelectedTier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.Property<string>("WizardState")
                        .HasColumnType("TEXT")
                        .HasColumnName("wizard_state");

                    b.HasKey("Id");

                    b.HasIndex("Completed");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_setup");
                });

            modelBuilder.Entity("Aura.Core.Data.AssetStateEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectVersionEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.RenderCheckpointEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Checkpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.SceneStateEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Scenes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectStateEntity", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Checkpoints");

                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
