// <auto-generated />
using System;
using Aura.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aura.Api.Data.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    [Migration("20251122175419_AddMissingDatabaseTables")]
    partial class AddMissingDatabaseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Aura.Core.Data.ActionLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResourceIds")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanBatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InverseActionType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InversePayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndoneByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Aura.Core.Data.AnalyticsRetentionSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AggregateOldData")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AggregationThresholdDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoCleanupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CleanupHourUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CollectHardwareMetrics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostTrackingRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDatabaseSizeMB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceMetricsRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackSuccessOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageStatisticsRetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("AnalyticsRetentionSettings");

                    b.HasData(
                        new
                        {
                            Id = "default",
                            AggregateOldData = true,
                            AggregationThresholdDays = 30,
                            AutoCleanupEnabled = true,
                            CleanupHourUtc = 2,
                            CollectHardwareMetrics = true,
                            CostTrackingRetentionDays = 365,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MaxDatabaseSizeMB = 500,
                            PerformanceMetricsRetentionDays = 30,
                            TrackSuccessOnly = false,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageStatisticsRetentionDays = 90
                        });
                });

            modelBuilder.Entity("Aura.Core.Data.AnalyticsSummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageCpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("AverageDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageMemoryUsageMB")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedGenerations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureBreakdown")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("MostUsedFeature")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MostUsedModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MostUsedProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderBreakdown")
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulGenerations")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCostUSD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("TotalGenerations")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRenderingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScenes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalVideoDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("PeriodStart");

                    b.HasIndex("PeriodType");

                    b.HasIndex("PeriodType", "PeriodId")
                        .IsUnique();

                    b.HasIndex("PeriodType", "PeriodStart");

                    b.ToTable("AnalyticsSummaries");
                });

            modelBuilder.Entity("Aura.Core.Data.AssetStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsTemporary");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "AssetType");

                    b.ToTable("AssetStates");
                });

            modelBuilder.Entity("Aura.Core.Data.AuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("TEXT")
                        .HasColumnName("changes");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ResourceType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("Action", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Aura.Core.Data.ConfigurationEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsSensitive");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Category", "IsActive");

                    b.HasIndex("Category", "UpdatedAt");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Aura.Core.Data.ContentBlobEntity", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReferencedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentHash");

                    b.HasIndex("ContentType");

                    b.HasIndex("LastReferencedAt");

                    b.HasIndex("ReferenceCount");

                    b.ToTable("ContentBlobs");
                });

            modelBuilder.Entity("Aura.Core.Data.CostTrackingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InputCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("InputPricePer1M")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutputCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("OutputPricePer1M")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UsageStatisticsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Provider");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UsageStatisticsId");

                    b.HasIndex("YearMonth");

                    b.HasIndex("Provider", "YearMonth");

                    b.HasIndex("YearMonth", "Timestamp");

                    b.ToTable("CostTracking");
                });

            modelBuilder.Entity("Aura.Core.Data.CustomTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LLMPipelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_pipeline_json");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ScriptStructureJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("script_structure_json");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoStructureJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("video_structure_json");

                    b.Property<string>("VisualPreferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visual_preferences_json");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDefault");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.ToTable("custom_templates");
                });

            modelBuilder.Entity("Aura.Core.Data.ExportHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Codec")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codec");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("InputFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("input_file");

                    b.Property<string>("OutputFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_file");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("preset_name");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL")
                        .HasColumnName("progress");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("export_history");
                });

            modelBuilder.Entity("Aura.Core.Data.HardwareSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Version");

                    b.ToTable("HardwareSettings");
                });

            modelBuilder.Entity("Aura.Core.Data.JobProgressHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentItem")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ElapsedMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedRemainingMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstageDetail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("JobId", "Timestamp");

                    b.ToTable("JobProgressHistory");
                });

            modelBuilder.Entity("Aura.Core.Data.JobQueueEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQuickDemo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EnqueuedAt");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("JobQueue");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaCollectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.ToTable("MediaCollections");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("Source");

                    b.HasIndex("Type");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.HasIndex("Type", "CreatedAt");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("Tag");

                    b.HasIndex("MediaId", "Tag")
                        .IsUnique();

                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UsedAt");

                    b.HasIndex("MediaId", "UsedAt");

                    b.ToTable("MediaUsages");
                });

            modelBuilder.Entity("Aura.Core.Data.PerformanceMetricsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DiskIOOperations")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MemoryUsedMB")
                        .HasColumnType("REAL");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NetworkBytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OutputFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PeakMemoryMB")
                        .HasColumnType("REAL");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("QueueWaitMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemInfo")
                        .HasColumnType("text");

                    b.Property<double?>("Throughput")
                        .HasColumnType("REAL");

                    b.Property<string>("ThroughputUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("OperationType");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Success");

                    b.HasIndex("Timestamp");

                    b.HasIndex("OperationType", "Timestamp");

                    b.HasIndex("Success", "Timestamp");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentWizardStep")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoSaveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceSpecJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.HasIndex("Status", "Category");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("ProjectStates");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMarkedImportant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("StorageSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimelineHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceSpecJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsMarkedImportant");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionType");

                    b.HasIndex("IsDeleted", "DeletedAt");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.HasIndex("ProjectId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("Aura.Core.Data.ProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Version");

                    b.ToTable("ProviderConfigurations");
                });

            modelBuilder.Entity("Aura.Core.Data.QueueConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuThrottleThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedJobRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobHistoryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryThrottleThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PauseOnBattery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryBaseDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryMaxDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("QueueConfiguration");

                    b.HasData(
                        new
                        {
                            Id = "default",
                            CpuThrottleThreshold = 90,
                            EnableNotifications = true,
                            FailedJobRetentionDays = 90,
                            IsEnabled = true,
                            JobHistoryRetentionDays = 30,
                            MaxConcurrentJobs = 2,
                            MemoryThrottleThreshold = 90,
                            PauseOnBattery = false,
                            PollingIntervalSeconds = 5,
                            RetryBaseDelaySeconds = 60,
                            RetryMaxDelaySeconds = 3600,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Aura.Core.Data.RenderCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckpointTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedScenes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScenes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointTime");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "StageName");

                    b.ToTable("RenderCheckpoints");
                });

            modelBuilder.Entity("Aura.Core.Data.RoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_role");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Permissions")
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsSystemRole");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            CreatedAt = new DateTime(2025, 11, 22, 17, 54, 19, 112, DateTimeKind.Utc).AddTicks(3839),
                            Description = "Full system access",
                            IsSystemRole = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            Permissions = "[\"admin.full_access\",\"users.manage\",\"config.write\",\"audit.view\"]",
                            UpdatedAt = new DateTime(2025, 11, 22, 17, 54, 19, 112, DateTimeKind.Utc).AddTicks(3840)
                        },
                        new
                        {
                            Id = "role-user",
                            CreatedAt = new DateTime(2025, 11, 22, 17, 54, 19, 112, DateTimeKind.Utc).AddTicks(3853),
                            Description = "Standard user access",
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER",
                            Permissions = "[\"projects.manage\",\"videos.create\",\"assets.manage\"]",
                            UpdatedAt = new DateTime(2025, 11, 22, 17, 54, 19, 112, DateTimeKind.Utc).AddTicks(3853)
                        },
                        new
                        {
                            Id = "role-viewer",
                            CreatedAt = new DateTime(2025, 11, 22, 17, 54, 19, 112, DateTimeKind.Utc).AddTicks(3865),
                            Description = "Read-only access",
                            IsSystemRole = true,
                            Name = "Viewer",
                            NormalizedName = "VIEWER",
                            Permissions = "[\"projects.view\",\"videos.view\"]",
                            UpdatedAt = new DateTime(2025, 11, 22, 17, 54, 19, 112, DateTimeKind.Utc).AddTicks(3865)
                        });
                });

            modelBuilder.Entity("Aura.Core.Data.SceneStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "SceneIndex");

                    b.ToTable("SceneStates");
                });

            modelBuilder.Entity("Aura.Core.Data.SettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Version");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Aura.Core.Data.SystemConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FFmpegPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ffmpeg_path");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_setup_complete");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_directory");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("system_configuration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSetupComplete = false,
                            OutputDirectory = "/home/runner/AuraVideoStudio/Output",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Aura.Core.Data.TemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsCommunityTemplate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_community_template");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PreviewImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_image");

                    b.Property<string>("PreviewVideo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_video");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating_count");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_category");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsCommunityTemplate");

                    b.HasIndex("IsSystemTemplate");

                    b.HasIndex("Category", "SubCategory");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("Aura.Core.Data.UploadSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedChunksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadedSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("UploadSessions");
                });

            modelBuilder.Entity("Aura.Core.Data.UsageStatisticsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureUsed")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OutputDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetryAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SceneCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenerationType");

                    b.HasIndex("JobId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Provider");

                    b.HasIndex("Success");

                    b.HasIndex("Timestamp");

                    b.HasIndex("GenerationType", "Timestamp");

                    b.HasIndex("Provider", "Timestamp");

                    b.HasIndex("Success", "Timestamp");

                    b.ToTable("UsageStatistics");
                });

            modelBuilder.Entity("Aura.Core.Data.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_suspended");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_ip");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_verified");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspendedReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("suspended_reason");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsSuspended");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Aura.Core.Data.UserQuotaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AiTokensPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ai_tokens_per_month");

                    b.Property<DateTime?>("AiTokensResetAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_tokens_reset_at");

                    b.Property<long>("AiTokensUsedThisMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ai_tokens_used_this_month");

                    b.Property<int?>("ApiRequestsPerDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_requests_per_day");

                    b.Property<DateTime?>("ApiRequestsResetAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("api_requests_reset_at");

                    b.Property<int>("ApiRequestsUsedToday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_requests_used_today");

                    b.Property<decimal?>("CostLimitUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_limit_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<int?>("MaxConcurrentJobs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_concurrent_jobs");

                    b.Property<int?>("MaxConcurrentRenders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_concurrent_renders");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<long?>("StorageLimitBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("storage_limit_bytes");

                    b.Property<long>("StorageUsedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("storage_used_bytes");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_cost_usd");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("VideosGeneratedThisMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("videos_generated_this_month");

                    b.Property<int?>("VideosPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("videos_per_month");

                    b.Property<DateTime?>("VideosResetAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("videos_reset_at");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_quotas");
                });

            modelBuilder.Entity("Aura.Core.Data.UserRoleEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Aura.Core.Data.UserSetupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("LastStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_step");

                    b.Property<string>("SelectedTier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.Property<string>("WizardState")
                        .HasColumnType("TEXT")
                        .HasColumnName("wizard_state");

                    b.HasKey("Id");

                    b.HasIndex("Completed");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_setup");
                });

            modelBuilder.Entity("Aura.Core.Data.AssetStateEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.CostTrackingEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.UsageStatisticsEntity", "UsageStatistics")
                        .WithMany()
                        .HasForeignKey("UsageStatisticsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsageStatistics");
                });

            modelBuilder.Entity("Aura.Core.Data.JobProgressHistoryEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.JobQueueEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.MediaCollectionEntity", "Collection")
                        .WithMany("MediaItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaTagEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.MediaEntity", "Media")
                        .WithMany("Tags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaUsageEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.MediaEntity", "Media")
                        .WithMany("Usages")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectVersionEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.RenderCheckpointEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Checkpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.SceneStateEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Scenes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aura.Core.Data.UserQuotaEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.UserEntity", "User")
                        .WithOne("Quota")
                        .HasForeignKey("Aura.Core.Data.UserQuotaEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Core.Data.UserRoleEntity", b =>
                {
                    b.HasOne("Aura.Core.Data.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aura.Core.Data.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaCollectionEntity", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Aura.Core.Data.MediaEntity", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectStateEntity", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Checkpoints");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Aura.Core.Data.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Aura.Core.Data.UserEntity", b =>
                {
                    b.Navigation("Quota");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
