// <auto-generated />
using System;
using Aura.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Aura.Api.Data.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    partial class AuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            // Configure all entities with their properties and relationships
            // This snapshot reflects the current state of the database schema
            // Generated from the InitialCreate migration

            modelBuilder.Entity("Aura.Core.Data.ExportHistoryEntity", b =>
                {
                    b.Property<string>("Id").IsRequired();
                    b.HasKey("Id");
                    b.ToTable("export_history");
                });

            modelBuilder.Entity("Aura.Core.Data.TemplateEntity", b =>
                {
                    b.Property<string>("Id").IsRequired();
                    b.HasKey("Id");
                    b.ToTable("templates");
                });

            modelBuilder.Entity("Aura.Core.Data.UserSetupEntity", b =>
                {
                    b.Property<string>("Id").IsRequired();
                    b.HasKey("Id");
                    b.ToTable("user_setup");
                });

            modelBuilder.Entity("Aura.Core.Data.SystemConfigurationEntity", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.ToTable("system_configuration");
                });

            modelBuilder.Entity("Aura.Core.Data.ConfigurationEntity", b =>
                {
                    b.Property<string>("Key").IsRequired();
                    b.HasKey("Key");
                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Aura.Core.Data.CustomTemplateEntity", b =>
                {
                    b.Property<string>("Id").IsRequired();
                    b.HasKey("Id");
                    b.ToTable("custom_templates");
                });

            modelBuilder.Entity("Aura.Core.Data.ActionLogEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectStateEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.ToTable("ProjectStates");
                });

            modelBuilder.Entity("Aura.Core.Data.SceneStateEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Scenes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.ToTable("SceneStates");
                });

            modelBuilder.Entity("Aura.Core.Data.AssetStateEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.ToTable("AssetStates");
                });

            modelBuilder.Entity("Aura.Core.Data.RenderCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany("Checkpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.ToTable("RenderCheckpoints");
                });

            modelBuilder.Entity("Aura.Core.Data.ProjectVersionEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd();
                    b.HasKey("Id");
                    b.HasOne("Aura.Core.Data.ProjectStateEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("Aura.Core.Data.ContentBlobEntity", b =>
                {
                    b.Property<string>("ContentHash").IsRequired();
                    b.HasKey("ContentHash");
                    b.ToTable("ContentBlobs");
                });

#pragma warning restore 612, 618
        }
    }
}
