using System;
using System.Collections.Generic;
using Aura.Core.Models;
using Aura.Core.Models.RAG;

namespace Aura.Core.Models.Ideation;

/// <summary>
/// Represents a creative video concept idea generated by AI
/// </summary>
public record ConceptIdea(
    string ConceptId,
    string Title,
    string Description,
    string Angle,                    // Storytelling approach (narrative, tutorial, case study, etc.)
    string TargetAudience,
    List<string> Pros,
    List<string> Cons,
    double AppealScore,              // 0-100 score for audience appeal
    string Hook,                     // Opening hook suggestion
    List<string>? TalkingPoints = null,  // Key talking points for the video
    Dictionary<string, double>? DemographicScores = null,  // Appeal scores by demographic
    DateTime? CreatedAt = null,
    // Enhanced high-value fields for better concept generation
    string? UniqueValue = null,      // What makes this concept stand out from competitors
    string? ContentGap = null,       // What competitors are missing that this addresses
    List<string>? KeyInsights = null, // Specific actionable insights
    List<string>? VisualSuggestions = null, // Specific visual ideas for the video
    string? MonetizationPotential = null, // High/Medium/Low with reasoning
    double? ViralityScore = null     // 0-100 score for potential virality
);

/// <summary>
/// Represents the requirements gathered for a video brief
/// </summary>
public record BriefRequirements(
    string Topic,
    string? Goal,                    // Purpose of the video
    string? Audience,                // Target audience description
    string? Tone,                    // Desired tone (formal, casual, humorous, etc.)
    int? DurationSeconds,            // Desired video length
    string? Platform,                // Target platform (YouTube, TikTok, Instagram, etc.)
    string[]? Keywords,              // SEO keywords
    Dictionary<string, string>? AdditionalDetails = null  // Any other collected information
);

/// <summary>
/// Represents a trending topic identified by the system
/// </summary>
public record TrendingTopic(
    string TopicId,
    string Topic,
    double TrendScore,               // 0-100 score indicating trend strength
    string? SearchVolume,            // Estimated search volume (if available)
    string? Competition,             // Competition level (low, medium, high)
    string? Seasonality,             // Seasonal relevance
    string? Lifecycle,               // rising, peak, declining
    List<string>? RelatedTopics,     // Clustered related topics
    DateTime? DetectedAt = null,
    TrendingTopicInsights? AiInsights = null,  // AI-generated analysis
    List<string>? Hashtags = null,   // Suggested hashtags
    double? TrendVelocity = null,    // Rate of growth/decline
    long? EstimatedAudience = null   // Estimated potential audience size
);

/// <summary>
/// AI-generated insights about a trending topic
/// </summary>
public record TrendingTopicInsights(
    string WhyTrending,              // Explanation of why this topic is trending
    string AudienceEngagement,       // Insights about audience engagement patterns
    List<string> ContentAngles,      // Recommended content angles for creators
    string DemographicAppeal,        // Target demographic information
    double ViralityScore             // 0-100 score for potential virality
);

/// <summary>
/// Represents a research finding gathered by AI
/// </summary>
public record ResearchFinding(
    string FindingId,
    string Fact,
    string? Source,                  // Source URL or citation
    double CredibilityScore,         // 0-100 credibility rating
    double RelevanceScore,           // 0-100 relevance to topic
    string? Example,                 // Real-world example illustrating the fact
    DateTime? GatheredAt = null
);

/// <summary>
/// Represents a scene in a visual storyboard
/// </summary>
public record StoryboardScene(
    int SceneNumber,
    string Description,
    string VisualStyle,              // Visual style suggestion
    int DurationSeconds,
    string Purpose,                  // Purpose of this scene in the narrative
    List<string>? ShotList,          // Detailed shot descriptions
    string? TransitionType = null    // Transition to next scene
);

/// <summary>
/// Represents a clarifying question from AI
/// </summary>
public record ClarifyingQuestion(
    string QuestionId,
    string Question,
    string Context,                  // Why this question is being asked
    List<string>? SuggestedAnswers,  // Optional suggested answer options
    string QuestionType              // "open-ended", "multiple-choice", "yes-no"
);

/// <summary>
/// Request to brainstorm concept variations
/// </summary>
/// <summary>
/// Request for brainstorming concepts
/// </summary>
/// <param name="Topic">Topic for brainstorming</param>
/// <param name="Audience">Target audience</param>
/// <param name="Tone">Desired tone</param>
/// <param name="TargetDuration">Target duration in seconds</param>
/// <param name="Platform">Target platform</param>
/// <param name="ConceptCount">Number of concepts to generate</param>
/// <param name="RagConfiguration">RAG configuration</param>
/// <param name="LlmParameters">LLM parameters</param>
/// <param name="LlmProvider">Override for LLM provider (e.g., "OpenAI", "Ollama", "Anthropic")</param>
/// <param name="LlmModel">Override for LLM model (e.g., "gpt-4o", "llama3.1:8b")</param>
public record BrainstormRequest(
    string Topic,
    string? Audience = null,
    string? Tone = null,
    int? TargetDuration = null,
    string? Platform = null,
    int? ConceptCount = null,
    RagConfiguration? RagConfiguration = null,
    LlmParameters? LlmParameters = null,
    string? LlmProvider = null,
    string? LlmModel = null
);

/// <summary>
/// Response containing brainstormed concepts
/// </summary>
public record BrainstormResponse(
    List<ConceptIdea> Concepts,
    string OriginalTopic,
    DateTime GeneratedAt
);

/// <summary>
/// Request to expand/clarify the brief
/// </summary>
public record ExpandBriefRequest(
    string ProjectId,
    BriefRequirements CurrentBrief,
    string? UserMessage = null
);

/// <summary>
/// Response with expanded brief or questions
/// </summary>
public record ExpandBriefResponse(
    BriefRequirements? UpdatedBrief,
    List<ClarifyingQuestion>? Questions,
    string? AiResponse
);

/// <summary>
/// Request for trending topics analysis
/// </summary>
public record TrendingTopicsRequest(
    string? Niche = null,
    int? MaxResults = 10
);

/// <summary>
/// Response containing trending topics
/// </summary>
public record TrendingTopicsResponse(
    List<TrendingTopic> Topics,
    DateTime AnalyzedAt
);

/// <summary>
/// Request for content gap analysis
/// </summary>
public record GapAnalysisRequest(
    string? Niche = null,
    List<string>? ExistingTopics = null,
    List<string>? CompetitorTopics = null
);

/// <summary>
/// Response with content gap analysis
/// </summary>
public record GapAnalysisResponse(
    List<string> MissingTopics,
    List<TrendingTopic> Opportunities,
    List<string> OversaturatedTopics,
    Dictionary<string, List<string>>? UniqueAngles  // Popular topic -> unique angles
);

/// <summary>
/// Request for research gathering
/// </summary>
public record ResearchRequest(
    string Topic,
    int? MaxFindings = 10
);

/// <summary>
/// Response with research findings
/// </summary>
public record ResearchResponse(
    List<ResearchFinding> Findings,
    string Topic,
    DateTime GatheredAt
);

/// <summary>
/// Request for storyboard generation
/// </summary>
public record StoryboardRequest(
    ConceptIdea Concept,
    int TargetDurationSeconds
);

/// <summary>
/// Response with visual storyboard
/// </summary>
public record StoryboardResponse(
    List<StoryboardScene> Scenes,
    string ConceptTitle,
    int TotalDurationSeconds,
    DateTime GeneratedAt
);

/// <summary>
/// Request to refine a concept
/// </summary>
public record RefineConceptRequest(
    ConceptIdea Concept,
    string RefinementDirection,      // "expand", "simplify", "adjust-audience", "merge"
    ConceptIdea? SecondConcept = null,  // For merging
    string? TargetAudience = null    // For audience adjustment
);

/// <summary>
/// Response with refined concept
/// </summary>
public record RefineConceptResponse(
    ConceptIdea RefinedConcept,
    string ChangesSummary
);

/// <summary>
/// Request to enhance/improve a video topic description
/// </summary>
public record EnhanceTopicRequest(
    string Topic,
    string? VideoType = null,
    string? TargetAudience = null,
    string? KeyMessage = null
);

/// <summary>
/// Response with enhanced topic description
/// </summary>
public record EnhanceTopicResponse(
    string EnhancedTopic,
    string OriginalTopic,
    DateTime GeneratedAt,
    string? Improvements = null
);

/// <summary>
/// Request to analyze prompt quality for video creation
/// </summary>
public record AnalyzePromptQualityRequest(
    string Topic,
    string? VideoType = null,
    string? TargetAudience = null,
    string? KeyMessage = null,
    RagConfiguration? RagConfiguration = null
);

/// <summary>
/// Response with prompt quality analysis results
/// </summary>
public record AnalyzePromptQualityResponse(
    int Score,
    string Level, // "excellent" | "good" | "fair" | "poor"
    Dictionary<string, int> Metrics, // length, specificity, clarity, actionability, engagement, alignment
    List<QualitySuggestion> Suggestions,
    DateTime GeneratedAt
);

/// <summary>
/// Quality suggestion with type and message
/// </summary>
public record QualitySuggestion(
    string Type, // "success" | "warning" | "info" | "tip"
    string Message
);

/// <summary>
/// Request for clarifying questions
/// </summary>
public record QuestionsRequest(
    string ProjectId,
    BriefRequirements? CurrentBrief = null
);

/// <summary>
/// Response with clarifying questions
/// </summary>
public record QuestionsResponse(
    List<ClarifyingQuestion> Questions,
    string Context
);

/// <summary>
/// Request to convert freeform idea into structured brief
/// </summary>
public record IdeaToBriefRequest(
    string Idea,
    string? TargetPlatform = null,      // Optional: "YouTube", "TikTok", "Instagram", etc. - or any custom platform description
    string? Audience = null,             // Optional: Freeform audience description (e.g., "tech-savvy millennials", "curious beginners")
    string? Language = null,
    int? VariantCount = null,            // Number of brief variants to generate (2-4)
    string? PreferredApproaches = null   // Optional: Freeform guidance for LLM (e.g., "make one funny, one serious, one like a documentary")
);

/// <summary>
/// Represents a generated brief variant with explanation
/// </summary>
public record BriefVariant(
    string VariantId,
    string Approach,                    // Freeform approach description from LLM (e.g., "humorous tutorial", "dramatic storytelling", "scientific deep-dive")
    Brief Brief,                        // Structured brief
    PlanSpec PlanSpec,                  // Suggested plan specification
    string Explanation,                 // Why this approach works for the idea
    double SuitabilityScore,            // 0-100 score for how well this fits the original idea
    List<string>? Strengths = null,     // Advantages of this approach
    List<string>? Considerations = null // Things to consider with this approach
);

/// <summary>
/// Response with generated brief variants
/// </summary>
public record IdeaToBriefResponse(
    List<BriefVariant> Variants,
    string OriginalIdea,
    DateTime GeneratedAt
);
